### ISSUE TITLE
Use google colab/kaggle notebooks

### ISSUE THREAD

**Issue by lolpie244** [kiyoon/jupynium.nvim#107]
Hi! Thanks for creating this plugin, it works perfectly while running locally. But is there any way to attach neovim to the google colab, or kaggle notebook?

**Comment by kiyoon** [comment]
I'm sorry but no. Their implementation is very different and they may not even support front-end API to control the notebook. The implementation becomes very tricky without such API.

**Comment by lolpie244** [comment]
Oh, it's really unfortunate. Anyway, thanks for the response!
