### ISSUE TITLE
JupyniumStartAndAttachToServer didn't open a browser

### ISSUE THREAD

**Issue by fecet** [kiyoon/jupynium.nvim#11]
Simply run JupyniumStartAndAttachToServer for a  `*.ju.py` file do nothing for me(no notebook open) and say "[Jupynium]: Jupynium sucessfully attached and in
itialised. Run `:JupyniumStartSync`"

then run `:JupyniumStartSync` gives me 
```
Jupynium: RPC channel closed. Stop sending all n
otifications.
[Jupynium]: Cancelling sync.
```

how to debug from there?

**Comment by kiyoon** [comment]
Hi,

First make sure Jupyter Notebook is running at localhost:8888

If it still doesn't work, let Jupynium running first from the command line: `jupynium` then try to start sync. It will print all the helpful logs.

**Comment by fecet** [comment]
The problem looks because newest selenium and newest firefox incompatible, I downgrade firefox and it works. What's the firefox version you are using?

**Comment by kiyoon** [comment]
Really? I've tried on many machines installing fresh new and it worked.. The version I have on Ubuntu is fron snap store and it's 108.0.2.

**Comment by fecet** [comment]
> Really? I've tried on many machines installing fresh new and it worked.. The version I have on Ubuntu is fron snap store and it's 108.0.2.

Or because the newest version didn't hook selenium to download a suitable driver? I don't familiar with selenium and have no idea what it does for its first run. Anyway, I'm using Arch and things I have tried are:

1. write a simple script to test selenium
    ```
    from selenium import webdriver
    driver = webdriver.Firefox()
    driver.get("https://www.selenium.dev/selenium/web/web-form.html")
    ``` 
    Firefox not open when I run it. 

2. downgrade Firefox, I randomly choose an old version like 100
4. run test script again, then it's work, I return to jupynium, it also works fine.
5. Update jupynium again, it's still work.

Don't know what fix this, but I'm happy now I can enjoy jupynium!

**Comment by kiyoon** [comment]
It could also be Selenium not detecting firefox binary. By installing it again it probably recognised it. Thanks a lot for leaving the helpful debugging steps and I'm glad it wasn't a big issue!
