### ISSUE TITLE
Jupynium server stop as long as I save the *.ju.py file

### ISSUE THREAD

**Issue by githubjacky** [kiyoon/jupynium.nvim#114]
First of all, thank you for creating such a beautiful plugin. I really appreciate your work.

**Describe the bug**
Can't save the *.ju.py while editing.

**To Reproduce**
1. ssh port forwarding for both `nvim_listen_addr` and `notebook_URL`
2. open the neovim and start the jupyter server in remote
3. open the jupynium server in local computer(no problem here)
4. save the *.ju.py file

**Expected behavior**
Jupynium server should not stop

**Logs in `/tmp/jupynium/logs/`**
<details>
<code>
jupynium.events_control:  197 - INFO - Event from nvim: Notification(type='notification', name='BufWritePre'
jupynium.cmds.jupynium:  559 - INFO - Nvim has been closed. Detaching nvim.
</code>
</details>

**Output of `jupynium --version`**
```
Jupynium v0.2.2
```

**Output of `nvim --version`**
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```

**Additional context**

**Comment by kiyoon** [comment]
Hi, did you save and close nvim? If the controlling nvim is no longer available, it will detach nvim.

**Comment by githubjacky** [comment]
Thanks for your reply! I didn't close the nvim. I just saved it.

**Comment by kiyoon** [comment]
Unfortunately the log isn't very helpful in this case.. According to it, while running `process_notification_event()` in `src/jupynium/event_control.py`, it threw an OSError somewhere thus logging `Nvim has been closed. Detaching nvim.` in line 559 of `src/jupynium/cmds/jupyniu.py`. Is it possible for you to debug the code a little and let me know where the error is happening?

**Comment by kiyoon** [comment]
Before that, can you set `auto_download_ipynb = false,` in the jupynium settings? It might be due to that functionality.

**Comment by kiyoon** [comment]
I think I get what's going wrong.. You're editing a file e.g. `/home/user/a.ju.py` in a server, and jupynium is trying to download ipynb to the local `/home/user/a.ipynb`. And when the local directory doesn't exist, it throws an OSError.

**Comment by githubjacky** [comment]
Exactly! If I set `auto_download_ipynb = false`. I can save the file correctly! Thanks for your help!

**Comment by githubjacky** [comment]
No problem. After installing the PyPI package from that branch, I can save the *.ju.py file and the log that is generated after saving the file:
<code>
jupynium.events_control:  197 - INFO - Event from nvim: Notification(type='notification', name='BufWritePre', args=[1, '`{ path }`'])

jupynium.events_control:  673 - WARNING - Failed to auto-download ipynb with error: [Errno 2] No such file or directory: '`{ path }`'.
Maybe a remote nvim is used and the path `{ path }` is not accessible on the local machine.
</code>

**Comment by kiyoon** [comment]
Thanks for testing! Looks good to go.
