### ISSUE TITLE
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox  executable

### ISSUE THREAD

**Issue by Gilk260** [kiyoon/jupynium.nvim#132]
**Describe the bug**
Error while starting sync with firefox.
Ubuntu 24.04.1 LTS
Mozilla Firefox 131.0
geckodriver 0.35.0 ( 2024-09-24)
NVIM v0.10.2

**To Reproduce**

1. Install [Jupinium](https://pypi.org/project/jupynium/) in a virtual env
2. Install Jupinium in neovim with `Lazy`, uncomment `build` part and specify `jupynium` folder in the virtualenv
3. Launch Jupynium with `:JupyniumStartAndAttachToServerInTrminal`

**Expected behavior**
Have Jupynium running.

**Logs in `/tmp/jupynium/logs/`**
The tmp directory path can be different in a different OS.  
Alternatively, run `:JupyniumStartAndAttachToServerInTerminal` to see the output directly in neovim.

<details>
<code>

jupynium.pynvim_helpers:   15 - INFO - nvim addr: /run/user/1001/nvim.17312.0
jupynium.pynvim_helpers:   34 - INFO - nvim attached
jupynium.pynvim_helpers:   38 - INFO - Initialising..
jupynium.pynvim_helpers:   39 - INFO - Communicating with channel_id 8
jupynium.cmds.jupynium:  517 - INFO - Namespace(notebook_URL='localhost:8888/nbclassic
', nvim_listen_addr='/run/user/1001/nvim.17312.0', attach_only=False, sleep_time_idle=
0.05, version=False, check_running=False, firefox_profiles_ini_path=None, firefox_prof
ile_name=None, jupyter_command=['jupyter'], notebook_dir=None, no_auto_close_tab=False
)
jupynium.cmds.jupynium:  102 - INFO - Using firefox profile: None
jupynium.cmds.jupynium:  623 - ERROR - Exception occurred
Traceback (most recent call last):
  File "/home/myuser/virtualenvs/my_env/lib/python3.12/site-packages/
jupynium/cmds/jupynium.py", line 526, in main
    with webdriver_firefox(
         ^^^^^^^^^^^^^^^^^^
  File "/home/myuser/virtualenvs/my_env/lib/python3.12/site-packages/
jupynium/cmds/jupynium.py", line 111, in webdriver_firefox
    return webdriver.Firefox(options=options, service=service)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/virtualenvs/my_env/lib/python3.12/site-packages/
selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/myuser/virtualenvs/my_env/lib/python3.12/site-packages/
selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/myuser/virtualenvs/my_env/lib/python3.12/site-packages/
selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/virtualenvs/my_env/lib/python3.12/site-packages/
selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/myuser/virtualenvs/my_env/lib/python3.12/site-packages/
selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox 
executable

[Process exited 0]

</code>
</details>

**Additional context**
I suppose there is a problem with the firefox_profiles_ini_path which is `None`, so it can't open Firefox properly.
I have added a line in the logs with all the args in input.

**Comment by kiyoon** [comment]
https://github.com/kiyoon/jupynium.nvim/issues/27#issuecomment-1405888448

Can you try this simple python code to see if you can run selenium with firefox no problem?

**Comment by Gilk260** [comment]
```
Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> driver = webdriver.Firefox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gillesrecouvreux/virtualenvs/onroad-us_env/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/gillesrecouvreux/virtualenvs/onroad-us_env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/gillesrecouvreux/virtualenvs/onroad-us_env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gillesrecouvreux/virtualenvs/onroad-us_env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/gillesrecouvreux/virtualenvs/onroad-us_env/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
```

**Comment by kiyoon** [comment]
Did you install firefox with Snap? I googled online and people say that the selenium may not pick up the correct geckodriver.

https://stackoverflow.com/questions/76846675/selenium-ubuntu22-bug-message-binary-is-not-a-firefox-executable

https://github.com/SeleniumHQ/selenium/issues/13169

Can you try the solution and see if it works (with the minimal code)?

**Comment by kiyoon** [comment]
I think, if you use the consistent version of firefox it will work.
For example,

Option 1: remove firefox from apt and use only the snap firefox and snap geckodriver  
Option 2: fix the profile missing error following this: <https://support.mozilla.org/en-US/kb/how-run-firefox-when-profile-missing-inaccessible>

**Comment by Gilk260** [comment]
I went with option 2, fix all, thanks
