### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by FelixKratz** [kiyoon/jupynium.nvim#14]
It seems when ever Jupynium is running it has a fairly high cpu utilization. I.e. when I run a regular jupyter notebook I will rarely see the cpu utilization (at idle) go above 1%, with jupynium running the python3 process is at a constant ~50% utilization. This could be due to an aggressive polling, but I am not sure.

**Comment by kiyoon** [comment]
Probably my system is different so I can't exactly reproduce this, but I think this will fix it! Feel free to reopen the issue if you still have the same problem.

**Comment by FelixKratz** [comment]
Indeed, it is down to ~5% now, thanks!
