### ISSUE TITLE
Can't install Jupynium - error with dependencies

### ISSUE THREAD

**Issue by bassamsdata** [kiyoon/jupynium.nvim#2]
**Describe the bug**
I can't install the jupynium with python3 and showing an error with dependencies. I tried installing it from nvim and from the terminal itself but it didn't install.

**To Reproduce**

1. just followed the instruction to install via lazy.nvim
2. once trying to install the issue appear.
<img width="1179" alt="Screen Shot 2023-01-12 at 9 39 31 PM" src="https://user-images.githubusercontent.com/105807570/212224745-8ebd1503-0b24-44f8-aa88-9443877106a7.png">
<img width="1136" alt="Screen Shot 2023-01-12 at 9 39 43 PM" src="https://user-images.githubusercontent.com/105807570/212224772-df5f7208-2dc8-41db-9c4b-d5f5ddfdeaa3.png">

**different way to reproduce:**
1. just do in the terminal: `pip3 install --user jupynium`
2. the issue will immediatley appear.
<img width="1416" alt="Screen Shot 2023-01-12 at 9 39 11 PM" src="https://user-images.githubusercontent.com/105807570/212224689-3cf64893-9001-4b00-a034-92bdd0e5df73.png">

**Expected behavior**
to be installed correctly

**The output**
<details>
<code>

Collecting jupynium
  Using cached jupynium-0.1.0.tar.gz (28 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AssertionError:
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'versioneer'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

</code>
</details>

**Output of `jupynium --version`**

```
Paste the output here
```

**Output of `nvim --version`**

```
NVIM v0.8.2
```

**Additional context**
OS: MacOS 12.6
Python: Python 3.10.9
I don't use conda or miniconda

**Comment by kiyoon** [comment]
Hi, which version of pip are you using? Can you upgrade the pip and retry? I think it requires one of the newer ones.

**Comment by bassamsdata** [comment]
I'm using `pip 22.3.1 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)`. I think this is the latest version.

**Comment by bassamsdata** [comment]
I tried upgrading it but yea this is the latest version:
`Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (22.3.1)`

**Comment by kiyoon** [comment]
Can you `pip install versioneer` and then install the plugin?  
This is usually not required as it should be downloaded automatically. I can't reproduce the problem, but if more people face the same problem I'll need to fix it.

**Comment by bassamsdata** [comment]
I'm afraid that the same issue persists. I'll try tomorrow to try some solutions and as last chance I may install miniconda and try to install it from there.

**Comment by bassamsdata** [comment]
I'd appreciate if you would provide me with the python and pip version that you have. I'll try installing the same version. It might solve the issue. thanks

**Comment by kiyoon** [comment]
My system python version is 3.10.6 with pip 22.3.1. I tried Conda with Python 3.10 and 3.11, with pip also 22.3.1 and all settings work for me..

**Comment by kiyoon** [comment]
Oh actually I can reproduce on Mac using brew python 3.10.  
If you make a venv and try again, it works.

**Comment by kiyoon** [comment]
It looks like a bug in brew python@3.10 or I don't know what's going on as I followed the PEP517 standard.  
Does using Python 3.11 by `brew install python@3.11` work?

**Comment by bassamsdata** [comment]
> It looks like a bug in brew python@3.10 or I don't know what's going on as I followed the PEP517 standard. Does using Python 3.11 by `brew install python@3.11` work?

It's the same issue with brew python@3.11 😔.


> Oh actually I can reproduce on Mac using brew python 3.10. If you make a venv and try again, it works.

It worked inside the venv but now I'm not sure how to solve the issue to be able to use the plugin 😂. I may leave it untill tomorrow.

**Comment by kiyoon** [comment]
Can you try with the PR or branch `fix-versioneer-dependency`? If it works on your side I will merge it to master.

**Comment by kiyoon** [comment]
It should work if you try it again! Sorry for the hassle. I don't have a Mac and I only tested with a friend's computer. I only tested inside venv / conda and not used the system one.

**Comment by bassamsdata** [comment]
> Can you try with the PR or branch `fix-versioneer-dependency`? If it works on your side I will merge it to master.

Oh I fell asleep last night, sorry for that.



> It should work if you try it again! Sorry for the hassle. I don't have a Mac and I only tested with a friend's computer. I only tested inside venv / conda and not used the system one.

no problem at all, I really liked the idea of this plugin and wanted it to work.
I'm gonna definitely try it and let you know the result. I hope it works.

**Comment by bassamsdata** [comment]
Firstly, I rally want to thank you for your support.

I installed jupynium successfully but it has some conflicts as the image below.

I tried to run it from nvim with `` then the notify says, it started the server then a firefox open and loading then immediately close by itself (I'm not sure if this the right behavior)

After that I run `` but nothing happens except the notify saying `cancelling Sync` 🫣 which surprising.

then nothing happen even if manually went to localhost, it shows can't connect.

I tried running from the terminal inside venv but it shows an error with `cmd` 

I'll try some other technique to sole the issue and gonna report back.

This is just to give a summary.

in nvim:
<img width="502" alt="Screen Shot 2023-01-13 at 4 02 07 PM" src="https://user-images.githubusercontent.com/105807570/212418740-c84bbe8c-00bb-42e6-b307-3eb358f295cf.png">

in the terminal:
<img width="896" alt="Screen Shot 2023-01-13 at 4 05 07 PM" src="https://user-images.githubusercontent.com/105807570/212418903-267b6be1-05fd-4662-baea-e077dad71d1e.png">

**Comment by kiyoon** [comment]
If you don't have Jupyter Notebook running at `localhost:8888` then the browser closes automatically. I should make this more user friendly, and I will keep improving the plugin.

Also, if you want to use the command line, you need to set the correct `--nvim_listen_addr`. This is not the notebook address. Check with `:echo v:servername` to see the nvim address, or launch nvim like `nvim --listen localhost:18898`

**Comment by bassamsdata** [comment]
yay, It worked after starting Jupyter Notebook.
Thank you so much. 

I'm exploring the options and configurations. Thanks again.

**Comment by kiyoon** [comment]
Good to hear! Thanks for letting me identify numerous issues already. If you have any more problem, feel free to add more comments or open another issue.

**Comment by kiyoon** [comment]
Note that this bug comes from homebrew's Python 3.10 & Python 3.11 pip.  
https://github.com/pypa/pip/issues/11539

This has been fixed, but not included in an official release yet.
