### ISSUE TITLE
Use magic commands in LSP-friendly way

### ISSUE THREAD

**Issue by fecet** [kiyoon/jupynium.nvim#28]
Jupytext support use magic commands like a comment, say,
```
# %time

2+3
```
would be regard as 
![image](https://user-images.githubusercontent.com/41792945/215340710-80236b7b-63f6-4650-9d4e-39ba3d71b940.png)

But that does not work for jupynium
![image](https://user-images.githubusercontent.com/41792945/215340774-a9df00d5-107a-4b8d-bc0f-b4a6469c6930.png)

Could we have something similar to allow using magic commands without breaking LSP?

**Comment by kiyoon** [comment]
Sounds like a useful feature request. I'll look into it soon!

**Comment by kiyoon** [comment]
Done!
