### ISSUE TITLE
Tridactyl

### ISSUE THREAD

**Issue by egolep** [kiyoon/jupynium.nvim#43]
Maybe this is a silly request and it's possible to do it already using something related to Firefox, but it would be very cool to be able to open the Firefox+Jupyter instance with some extensions.
In particular, I'm thinking of Tridactyl, but I think other people would probably be interested in other extensions.

**Comment by kiyoon** [comment]
You can set firefox_profiles_ini_path and firefox_profile_name when you set it up. Then it will load your profile with extensions. You can also make a separate profile with minimal extensions. I saw that some extensions can interfere with starting Jupyter server

**Comment by egolep** [comment]
That's what I tried to do but it didn't work. Probably something wrong with my firefox profile. Thanks for your reply!

**Comment by kiyoon** [comment]
@egolep Okay, how did you install firefox? Snap? Depending on how there are different paths. If you configure it correctly, it will load the extensions
