### ISSUE TITLE
Kernel interrupt and run all cells

### ISSUE THREAD

**Issue by sho-87** [kiyoon/jupynium.nvim#45]
Would love to see the following being implemented at some point:

- `Jupynium InterruptKernel`
- `Jupynium RunAllCells`

(Is there currently a way to run all cells without manually executing every cell in order?)

**Comment by kiyoon** [comment]
Interrupt should be implemented. But you can select entire text in visual mode and execute, then it will execute entire cells

**Comment by kiyoon** [comment]
Added `:JupyniumKernelInterrupt`. Note that `:JupyniumRestartKernel` and `:JupyniumSelectKernel` name has been changed to `:JupyniumKernelRestart` and `:JupyniumKernelSelect`. I thought I'd start to group commands.
