### ISSUE TITLE
Can't figure out how to setup remote connection

### ISSUE THREAD

**Issue by huyiqun** [kiyoon/jupynium.nvim#78]
Hello, thanks for creating this plugin! I have some issue setting up the connection in the remote neovim + local firefox setting for jupynium.

Here's what I tried:
* in the remote, installed the jupynium.nvim plugin and launched the neovim with `nvim --listen localhost:8080 test.ju.py`
* on my local machine, set up the `jupynium` env and installed all dependency packages and launched jupynium with `jupynium --nvim_listen_addr localhost:8898`
with port forwarding for ssh:
```
Host ec2
	HostName xx
	User xx
	ProxyJump xx
	LocalForward 8898 127.0.0.1:8080
```

When the jupynium command runs, here's the terminal print:
```
jupynium.pynvim_helpers:   11 - INFO - nvim addr: localhost:8898
jupynium.pynvim_helpers:   30 - INFO - nvim attached
jupynium.pynvim_helpers:   34 - INFO - Initialising..
jupynium.pynvim_helpers:   35 - INFO - Communicating with channel_id 7
jupynium.cmds.jupynium:   90 - INFO - Using firefox profile: None
selenium.webdriver.common.selenium_manager:  115 - INFO - Executing: ~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/selenium/webdriver/common/macos/selenium-manager --browser firefox --output json
[I 16:41:55.667 NotebookApp] 302 GET / (127.0.0.1) 0.330000ms
[I 16:41:55.673 NotebookApp] 302 GET /tree? (127.0.0.1) 0.390000ms
```
However, I see in the opened browser, the address is 
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/10877536/234112755-9f7644bf-959b-4caa-a211-8b5ddbffda47.png">
(note: the port is 8888, not 8898)
It seems to started a local jupyter notebook instance instead of connecting to the remote. On the other hand, in the remote neovim, it does like there's some connection established with all the available commands:
![image](https://user-images.githubusercontent.com/10877536/234113187-4cf9bb29-7d8e-4ef1-898b-7633cf9b468e.png)

I am not sure if I missed anything or did anything obviously wrong. Any help would be really appreciated thanks!

**Comment by kiyoon** [comment]
Hi, you also need to open the notebook server on remote. If there's no server running, it will automatically open locally for you. It doesn't automatically open notebook remotely. Hope this helps.

**Comment by huyiqun** [comment]
Should I open notebook server on the remote before I launch neovim or after? and with `jupyter notebook` or `jupynium` as the command? Here's what I tried (all on remote) but not much luck

* If first run `nvim --listen localhost:8080 test.ju.py` then`jupynium --nvim_listen_addr localhost:8080`, it returned an error saying unable to find binary.
* If first run `nvim --listen localhost:8080 test.ju.py` then `jupyter notebook --no-browser --port=8080`, it logged `The port 8080 is already in use, trying another port.` and changed to another port.
* If first run `jupynium` first, then it returned `Timeout while waiting for nvim to start`.
* If first run `jupyter notebook --no-browser --port=8080`, then `neovim --listen localhost:8080 test.ju.py`, no error returned on remote side, but doing `jupynium --nvim_listen_addr localhost:8898` does not open any browser locally.

For the port, I added `LocalForward 8898 127.0.0.1:8080` in the config (see above) - is this not legitimate? I launch jupynium locally with `jupynium --nvim_listen_addr localhost:8898, so I think the port matches?

**Comment by kiyoon** [comment]
You need to run Notebook before launching Jupynium. It doesn't matter whenever you open neovim.

Nvim port and notebook port is separate. I think you're trying to use the same port. I recommend launching notebook with the default port (8888) and nvim with something different. Then ssh port forwarding should forward both ports. Jupynium should use nvim's port and not 8888 (Jupyter Notebook's port)

**Comment by huyiqun** [comment]
It seems like I cannot forward port 8888 for the notebook as it is occupied by something else as I got this message
```
bind [127.0.0.1]:8888: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 8888
Could not request local forwarding.
```

To workaround this, if I forward both ports with
```
	LocalForward 8080 127.0.0.1:8080
	LocalForward 8898 127.0.0.1:8898
```
so that I can use these two ports separately for nvim and notebook.  Is the following the correct workflow?
1. run `jupyter notebook --port=8080` on remote
2. run `nvim --listen localhost:8898 test.ju.py` on remote
3. run `jupynium --nvim_listen_addr localhost:8898` on local

I am a bit curious as if nvim and notebook use two separate ports, how do they communicate with each other?

**Comment by kiyoon** [comment]
That's almost correct, but in 3, you need to also specify `--notebook_URL localhost:8080` (I can't remember the name. See `-h` for help.).

Jupynium doesn't directly communicate with Jupyter Notebook. Instead, it interacts through fromt-end via Selenium. So the web browser interface is all you need, but you need to know the URL so you can open it.

**Comment by kiyoon** [comment]
Another thing to note is that, most of the options you configured in `require("jupynium").setup` wouldn't be applied when you're using the CLI. You need to pass the arguments directly to the CLI. The CLI is independent from the vim olugin setup, and you can attach to neovim with no plugin installed. That's why you need to pass `--notebook_URL`

**Comment by huyiqun** [comment]
> That's almost correct, but in 3, you need to also specify --notebook_URL localhost:8080

This is really helpful! So I currently have on the remote a jupyter notebook server running on port 8888 and `nvim --listen localhost:8898 test.ju.py`. On local I run `jupynium --notebook_URL 8888 --nvim_listen_addr localhost:8898`. With this, the firefox browser successfully launched and connected to the remote notebook server.

But I could not seem to edit/sync the remote neovim. When I tried `JupyniumStartSync test.ipynb`, the firefox browser window closes automatically (see stderr below). In neovim it prints `cancelling sync...` then `Jupynium: RPC channel closed. Stop sending all notifications`.  Is this referring to what you said that the plugin does not apply to CLI process and how should I set it up correctly?

- local jupyinium process std error
```jupynium --notebook_URL localhost:8888 --nvim_listen_addr localhost:8898
jupynium.pynvim_helpers:   11 - INFO - nvim addr: localhost:8898
jupynium.pynvim_helpers:   30 - INFO - nvim attached
jupynium.pynvim_helpers:   34 - INFO - Initialising..
jupynium.pynvim_helpers:   35 - INFO - Communicating with channel_id 6
jupynium.cmds.jupynium:   90 - INFO - Using firefox profile: None
selenium.webdriver.common.selenium_manager:  115 - INFO - Executing: ~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/selenium/webdriver/common/macos/selenium-manager --browser firefox --output json
jupynium.events_control:  195 - INFO - Event from nvim: ['request', 'start_sync', [1, '', True, [''], 'python', '~/.pyenv/versions/3.9.16/envs/jupynium'], <pynvim.msgpack_rpc.async_session.Response object at 0x1023929a0>]
jupynium.selenium_helpers:   31 - ERROR - Timed out waiting for page to load
Traceback (most recent call last):
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/jupynium/selenium_helpers.py", line 25, in wait_until_notebook_list_loaded
    WebDriverWait(driver, timeout).until(
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:398:5
element.find/</<@chrome://remote/content/marionette/element.js:300:16

urllib3.connectionpool:  812 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10245d9d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/604f6b7a-bd07-4ebd-a8b1-cd16d4a14bcf/element
urllib3.connectionpool:  812 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10245da60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/604f6b7a-bd07-4ebd-a8b1-cd16d4a14bcf/element
urllib3.connectionpool:  812 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10245d7f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/604f6b7a-bd07-4ebd-a8b1-cd16d4a14bcf/element
jupynium.cmds.jupynium:  507 - ERROR - Uncaught exception occurred while processing events. Detaching nvim.
Traceback (most recent call last):
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "~/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "~/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "~/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "~/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "~/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10245d340>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/jupynium/cmds/jupynium.py", line 502, in main
    status, rpcrequest_event = process_events(nvim_info, driver)
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/jupynium/events_control.py", line 205, in process_events
    status, request_event = process_request_event(nvim_info, driver, event)
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/jupynium/events_control.py", line 429, in process_request_event
    start_sync_with_filename(
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/jupynium/events_control.py", line 295, in start_sync_with_filename
    new_btn = driver.find_element(By.ID, "new-buttons")
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53492): Max retries exceeded with url: /session/604f6b7a-bd07-4ebd-a8b1-cd16d4a14bcf/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10245d340>: Failed to establish a new connection: [Errno 61] Connection refused'))
urllib3.connectionpool:  812 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10245dbe0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/604f6b7a-bd07-4ebd-a8b1-cd16d4a14bcf/window/handles
urllib3.connectionpool:  812 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10248f040>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/604f6b7a-bd07-4ebd-a8b1-cd16d4a14bcf/window/handles
urllib3.connectionpool:  812 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10248f220>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/604f6b7a-bd07-4ebd-a8b1-cd16d4a14bcf/window/handles
jupynium.cmds.jupynium:  536 - INFO - Browser disconnected. Quitting Jupynium.
urllib3.connectionpool:  812 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10248f430>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/604f6b7a-bd07-4ebd-a8b1-cd16d4a14bcf
urllib3.connectionpool:  812 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10245dca0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/604f6b7a-bd07-4ebd-a8b1-cd16d4a14bcf
urllib3.connectionpool:  812 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10245da90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/604f6b7a-bd07-4ebd-a8b1-cd16d4a14bcf
selenium.webdriver.firefox.webdriver:  221 - ERROR - Unable to remove profile specific paths.
Traceback (most recent call last):
  File "~/.pyenv/versions/3.8.16/envs/jupynium/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 217, in quit
    rmtree(self.profile.path)
  File "~/.pyenv/versions/3.8.16/lib/python3.8/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "~/.pyenv/versions/3.8.16/lib/python3.8/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/pj/0w6n21qx0g74v2ddzs7c19vw0000gr/T/tmpyfinzj6q'
jupynium.cmds.jupynium:  552 - SUCCESS - Piecefully closed as the browser is closed.
```

**Comment by kiyoon** [comment]
It could be a bug. Are you using virtualenv? I'll try to reproduce the problem and let you know. Thanks!

**Comment by kiyoon** [comment]
What version of Jupyter Notebook are you running? I think it couldn't detect the home page of the Notebook correctly.

**Comment by huyiqun** [comment]
Yes, I used pyenv to create a virtualenv to test. Here's the jupyter package versions on the remote
![image](https://user-images.githubusercontent.com/10877536/234725567-df48b455-0711-44d4-a578-129efd61799f.png)

Btw, I actually ran into an error when installing the plugin with `use { "kiyoon/jupynium.nvim", run = "pip3 install --user ." }`. So I ended up installing the `requirements.txt`from the repo manually for this virtualenv and removed the `run` field in the neovim config.

**Comment by kiyoon** [comment]
I just tested with the master branch of Jupynium (0.2.1.dev16+g4f2c1ea) and I can't reproduce it.

Before syncing, make sure your home page is the Jupyter Notebook file list like this:

![image](https://user-images.githubusercontent.com/12980409/234732080-97512565-5075-4d23-8e2c-569c51f1a7e9.png)

It shouldn't be showing a different screen like password/token input page.

**Comment by huyiqun** [comment]
Ah, I think that's the problem. Whether I tried it with a local or remote notebook, it always asks for token or password. However, with local notebook server, after I input the token, I can successfully sync between neovim and the notebook in the browser. With remote server, after input token (or password), it landed on the folder page, but syncing with neovim failed as above.

**Comment by huyiqun** [comment]
I also tried launching remote jupyter notebook server with `jupyter notebook --no-browser --NotebookApp.token='' --NotebookApp.password=''`. In this case, the browser does land directory on the file tree page (without asking for token/password) but the same issue still persists.

**Comment by kiyoon** [comment]
So it only works locally and not remotely? Maybe it's a network issue then. Do you think your internet has firewall, VPN, proxy etc. that will potentially confuse the connection? It's weird as you have already attached to Neovim with no problem.

**Comment by kiyoon** [comment]
Wait, you said remote Notebook is the problem? Even if I test on the remote Neovim and Notebook it works for me.

You told me there was an issue with the installation. Can you describe that further?

**Comment by kiyoon** [comment]
Which OS are you using? Is it Linux?

**Comment by huyiqun** [comment]
Ah I think I figured out the issue. Before, I created a virtualenv (with pyenv) and activated locally for a folder. When I tried install the package (with packer.nvim), I ran into the error which somehow I can no longer reproduce... but previously because of that error, I did `pip install -r requirements.txt` in the virtualenv and that seems not have correctly installed the jupynium plugin.

I think the idea is that jupyter notebook server and the kernels are from the local virtualenv, but the required python packages for `jupynium` as a plugin needs to be installed globally as some of the commands are not executed from the local folder so it is not invoking the local virtualenv PATH etc.

So the main problem is I mixed the local virtualenv where the jupyter notebook server runs and the python which the plugin actually uses 😳

Overall things are starting to work, thanks so much for all the help! I do have a few minor issues I'd like to learn about. One is when I do `:JupyniumStartSync test.ipynb` for a `notebook.ju.py` file for instance. 
![image](https://user-images.githubusercontent.com/10877536/234999998-78ed81e2-afd7-42ad-b90b-41cc97d3907a.png)
If this `test.ipynb` already exists in the folder, it will not sync with that file but seemed to create a new `Untitled.ipynb` file.
![image](https://user-images.githubusercontent.com/10877536/235000074-ae7d4db2-4c1c-4120-a3eb-3c4156299424.png)
 Is that expected behavior? 
Here's the stdout from the server
![image](https://user-images.githubusercontent.com/10877536/234999896-0fe8607d-7196-4c44-9004-a6da40a42d41.png)

**Comment by kiyoon** [comment]
Glad that you managed to figure it out!

And it should select the existing file automatically. You can omit the `.ipynb` suffix as well.

From the log, it looks like Jupynium couldn't find any file from the home page file list. If there's the file on the home page, then it will open that file. If not it will create a file and rename it. It looks like it couldn't find the file.

If you try `:JupyniumStartSync test` does it work? It could be a bug that happens when you add the file extension.
