### ISSUE TITLE
On debian 12 ain't working

### ISSUE THREAD

**Issue by DamaKubu** [kiyoon/jupynium.nvim#87]
When I run :JupyniumStartAndAttachToServer from nvim 0.10 no tab open just, says it's attached and synced and prompts me to use 

![jupyniumNotWork0](https://github.com/kiyoon/jupynium.nvim/assets/105709788/e19cfb25-40e4-45f6-b3bb-551b2be4d37c)

Though then using the command JupyniumStartSync command, says cancelling sync and does nothing.

![jupynium1](https://github.com/kiyoon/jupynium.nvim/assets/105709788/94681477-2adf-4dd0-9a1d-b0e857add2ce)

Tried many ways to get jupynium working, but couldn't.

I believe all requirements are installed.

**Output of `jupynium --version`**

```
Jupynium v0.2.0

```

**Output of `nvim --version`**

```
NVIM v0.10.0-dev-766+gef44e5972
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info

```

**Output of `:JupyniumStartAndAttachToServerInTerminal`**

```
jupynium.pynvim_helpers: 11 - INFO - nvim addr: /run/user/1000/nvim.25647.0
jupynium.pynvim_helpers: 30 - INFO - nvim attached
jupynium.pynvim_helpers: 34 - INFO - Initialising..
jupynium.pynvim_helpers: 35 - INFO - Communicating with channel_id 5
jupynium.cmds.jupynium: 90 - INFO - Using firefox profile: None
jupynium.cmds.jupynium: 539 - ERROR - Exception occurred
Traceback (most recent call last):
File "/home/aokis/darbas/virtualibook/lib/python3.11/site-packages/jupynium/cmds/jupynium.py", line
452, in main
with webdriver_firefox(
^^^^^^^^^^^^^^^^^^
File "/home/aokis/darbas/virtualibook/lib/python3.11/site-packages/jupynium/cmds/jupynium.py", line
96, in webdriver_firefox
return webdriver.Firefox(profile, service_log_path=os.path.devnull)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.init() got an unexpected keyword argument 'service_log_path'

[Process exited 0]


```

**Comment by fecet** [comment]
What if you open a notebook in your firefox, like at tab 2, then `:JupyniumStartSync 2`? I often used jupynium in this way

**Comment by kiyoon** [comment]
Can you run ` :JupyniumStartAndAttachToServerInTerminal` and paste the error output here?

**Comment by DamaKubu** [comment]
> 
jupynium.pynvim_helpers:   11 - INFO - nvim addr: /run/user/1000/nvim.25647.0
jupynium.pynvim_helpers:   30 - INFO - nvim attached
jupynium.pynvim_helpers:   34 - INFO - Initialising..
jupynium.pynvim_helpers:   35 - INFO - Communicating with channel_id 5
jupynium.cmds.jupynium:   90 - INFO - Using firefox profile: None
jupynium.cmds.jupynium:  539 - ERROR - Exception occurred
Traceback (most recent call last):
  File "/home/aokis/darbas/virtualibook/lib/python3.11/site-packages/jupynium/cmds/jupynium.py", line 
452, in main
    with webdriver_firefox(
         ^^^^^^^^^^^^^^^^^^
  File "/home/aokis/darbas/virtualibook/lib/python3.11/site-packages/jupynium/cmds/jupynium.py", line 
96, in webdriver_firefox
    return webdriver.Firefox(profile, service_log_path=os.path.devnull)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service_log_path'

[Process exited 0]

**Comment by DamaKubu** [comment]
> What if you open a notebook in your firefox, like at tab 2, then `:JupyniumStartSync 2`? I often used jupynium in this way

If I write that command then nvim gives error:
 E492: Not an editor command: JupyniumStartSync 2

I tried to install vim-magma same E492 problem, so it's likely something's wrong with my setup.

**Comment by DamaKubu** [comment]
> Can you run ` :JupyniumStartAndAttachToServerInTerminal` and paste the error output here?
> 
> Alternatively, logs can be found in `/tmp/jupynium/logs`

Sure! it gives:

jupynium.pynvim_helpers: 11 - INFO - nvim addr: /run/user/1000/nvim.25647.0
jupynium.pynvim_helpers: 30 - INFO - nvim attached
jupynium.pynvim_helpers: 34 - INFO - Initialising..
jupynium.pynvim_helpers: 35 - INFO - Communicating with channel_id 5
jupynium.cmds.jupynium: 90 - INFO - Using firefox profile: None
jupynium.cmds.jupynium: 539 - ERROR - Exception occurred
Traceback (most recent call last):
File "/home/aokis/darbas/virtualibook/lib/python3.11/site-packages/jupynium/cmds/jupynium.py", line
452, in main
with webdriver_firefox(
^^^^^^^^^^^^^^^^^^
File "/home/aokis/darbas/virtualibook/lib/python3.11/site-packages/jupynium/cmds/jupynium.py", line
96, in webdriver_firefox
return webdriver.Firefox(profile, service_log_path=os.path.devnull)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.init() got an unexpected keyword argument 'service_log_path'

[Process exited 0]

**Comment by fecet** [comment]
https://github.com/kiyoon/jupynium.nvim/issues/80

**Comment by kiyoon** [comment]
If you installed using `pip install jupynium` it will install slightly old version. If you use plugin manager like lazy.nvim, it will install the latest commit. Maybe you need to remove and reinstall the plugin using lazy.nvim.
