### ISSUE TITLE
Refresh line_types cause performance degradation(probably)

### ISSUE THREAD

**Issue by fecet** [kiyoon/jupynium.nvim#89]
During may hack in https://github.com/kiyoon/jupynium.nvim/pull/88, I found that jupynium will call `cells.line_types_entire_buf` even without editing. That seems result in slow scroll in large files when jupynium is enabled.

**Comment by kiyoon** [comment]
Is it because of the `get_fold` implementation in #88? Maybe ufo callback is being called too often?

**Comment by fecet** [comment]
The problem persisted after I set `dev=false` so that's should be irrelevant with my PR.
Cloud you confirm this by something like
```lua
-- jupynium.nvim/lua/jupynium/highlighter.lua
function M.update()
  if not M.is_enabled() then
    return
  end

  local end_of_file = vim.fn.line "$"
  local line_types = cells.line_types_entire_buf()
  print("Call me")

```

> Maybe the function return table can be cached and reused if the buffer is not changed

Yeah I agree this is a clever approach
