### ISSUE TITLE
Write large binary in logs

### ISSUE THREAD

**Issue by fecet** [kiyoon/jupynium.nvim#93]
Arch linux use memory as `/tmp` so I fount this as it result in memory leak in my end. 

A typical logs looks like

![image](https://github.com/kiyoon/jupynium.nvim/assets/41792945/fa1b9244-65cc-46ea-bfcb-d6b7cdc74d1c)

Delete this line make the file size reduce to `900k` from `30M`. 30M is not a dealbreaker, but it can also goes to `8G` and I cannot open it yet.

[2023-09-14_20-19-13.log](https://github.com/kiyoon/jupynium.nvim/files/12616385/2023-09-14_20-19-13.log)

**Comment by kiyoon** [comment]
We have two options.

1. Exclude the specific selenium log when writing
2. Log with INFO level. It may be harder to debug some specific issues

**Comment by fecet** [comment]
I think jupynium's log is just too active, the log grow up to ~200k lines in 10 minutes. Is it expected?
